### PR TITLE
#161 landing page UI

### PR DESCRIPTION
**Pull request by adamJUK**
Fixed Lint issue.

### CODE REVIEW

**Comment by U-ways** [comment]
Nothing urgent, but the merge for this branch is broken. (Modified the history of 132 unrelated files)

I provided a fixed example on branch `#161-Landing-Page-UI-fixed-merge`

Can you please have a look at that branch when you're free and let me know so we can apply the fix for this PR?

To be exact can you look at:

- `HomePage.vue`
- `MemberCard.vue`
- `tailwind.config.vie`

In `#161-Landing-Page-UI-fixed-merge` and let me know if the conflicted files that been are correct?

So you guys don't lose any changes from this PR? (Conflicted changes from newer front end changes)

**Review by U-ways — DISMISSED** [review]
Please see: https://github.com/U-ways/choppa/pull/183#issuecomment-774546271

**Comment by adamJUK** [comment]
Unfortunately no as the homepage on the "fixed" branch is the massively outdated one.

**Review by brett-taylor — APPROVED** [review]

**Comment by U-ways** [comment]
👍🏼

**Pull request merged**
